import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import NavBar from "../components/NavBar";
import "./globals.css";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const beVietnam = localFont({
  src: [
    { path: "../public/fonts/BeVietnamPro-Thin.ttf", weight: "100" },
    { path: "../public/fonts/BeVietnamPro-ExtraLight.ttf", weight: "200" },
    { path: "../public/fonts/BeVietnamPro-Light.ttf", weight: "300" },
    { path: "../public/fonts/BeVietnamPro-Regular.ttf", weight: "400" },
    { path: "../public/fonts/BeVietnamPro-Medium.ttf", weight: "500" },
    { path: "../public/fonts/BeVietnamPro-SemiBold.ttf", weight: "600" },
    { path: "../public/fonts/BeVietnamPro-Bold.ttf", weight: "700" },
    { path: "../public/fonts/BeVietnamPro-ExtraBold.ttf", weight: "800" },
    { path: "../public/fonts/BeVietnamPro-Black.ttf", weight: "900" },
  ],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${beVietnam.className} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NavBar />
          <main>{children}</main>
          <Footer />  
        </ThemeProvider>
      </body>
    </html>
  );
}
